version: "3.8"

services:
  server_1:
    build: ./backend
    ports:
      - "3001:3000"

  server_2:
    build: ./backend
    ports:
      - "3002:3000"

  server_3:
    build: ./backend
    ports:
      - "3003:3000"

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    depends_on:
      - server_1
      - server_2
      - server_3
